package com.githubanalyzer.domain;

import com.githubanalyzer.domain.enums.AlertType;
import com.githubanalyzer.domain.enums.Severity;

import java.util.Objects;

/**
 * Represents a health or quality alert raised against a repository.
 *
 * <p>Alerts are generated by {@code AlertRule} implementations inside the
 * {@code RuleBasedAlertEngine}. Multiple alerts can be active simultaneously.
 *
 * <p>Immutable — created via the static factory method {@link #of}.
 */
public final class Alert {

    private final AlertType type;
    private final String message;
    private final Severity severity;

    private Alert(AlertType type, String message, Severity severity) {
        this.type = Objects.requireNonNull(type, "AlertType must not be null");
        this.message = Objects.requireNonNull(message, "message must not be null");
        this.severity = Objects.requireNonNull(severity, "Severity must not be null");
    }

    /**
     * Factory method — preferred over constructor for readability.
     *
     * @param type     the classification of this alert
     * @param message  human-readable message shown in the UI
     * @param severity visual severity level
     * @return a new Alert instance
     */
    public static Alert of(AlertType type, String message, Severity severity) {
        return new Alert(type, message, severity);
    }

    public AlertType getType() {
        return type;
    }

    public String getMessage() {
        return message;
    }

    public Severity getSeverity() {
        return severity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Alert alert)) return false;
        return type == alert.type;   // One alert per type is sufficient for equality
    }

    @Override
    public int hashCode() {
        return Objects.hash(type);
    }

    @Override
    public String toString() {
        return "Alert{type=" + type + ", severity=" + severity + ", message='" + message + "'}";
    }
}
